x-config:
  - &NODE_BUILDER "hoteleria"
  - &CONTAINER_NAME "angular-container"
  - &BUILDER_CONTAINER_NAME "node-builder"


services:
    dev:
      image: *NODE_BUILDER
      container_name: *CONTAINER_NAME
      ports:
        - '4200:4200'
      volumes:
        - ./src:/usr/src/app/src
      command: ng serve --host 0.0.0.0 --poll 200
